services:
  web:
    labels:
      caddy: proxy.mariozechner.at
      caddy.reverse_proxy: '{{upstreams 80}}'
    networks:
      - caddy-network
      - internal
  backend:
    # Backend only needs internal network, not exposed to caddy directly
    networks:
      - internal
networks:
  caddy-network:
    external: true
  internal:
